FROM node:18-alpine

WORKDIR /app

# Instalar dependências
COPY package*.json ./
RUN npm install

# Copiar código fonte
COPY . .

# Expor porta para o servidor de desenvolvimento
EXPOSE 4200

# Iniciar servidor de desenvolvimento
CMD ["npm", "start", "--", "--host", "0.0.0.0"]